In [1]:
import numpy as np
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [2]:
b = np.array([1,2,3,4,5,6,7])
b[0:6]

array([1, 2, 3, 4, 5, 6])

In [6]:
a = np.array([1,2,3,4,5,6,7,8,9])
b=a.reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
d = np.array_split(a,4)
d

[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [12]:
np.where(a%2==1)

(array([0, 2, 4, 6, 8], dtype=int64),)